apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: my-namespace
spec:
  containers:
  - name: container-1
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: my-namespace
spec:
  containers:
  - name: container-2
    image: nginx